### ISSUE TITLE
/<fqdn>/swagger/ loads as /swagger/#/projects

### ISSUE THREAD

**Issue by dmspils** [faloker/purify#36]
Looking on the [docs](https://faloker.gitbook.io/purify/swagger), it says that the swagger interface is available at `https://<fqdn>/swagger/`

When I hit that URL, it returns as `/swagger/#/projects` and doesn't load the swagger ui. Is there anything obvious that I've missed as the rest of purify seems to work well, including the api?

**Comment by faloker** [comment]
It is strange, because it should redirect you to the Swagger UI, when you hit `https://<fqdn>/swagger/`. Like this https://purify-demo.herokuapp.com/swagger/.

But, I guess that it will work only for a standalone setup. In case of deployment with Nginx, it will not forward requests to the `/swagger` path to the API:
```
    location / {
      root /app;
      index index.html;
      try_files $uri $uri/ /index.html;
    }

    location /api {
      proxy_pass http://api:3000;
    }
```
Therefore, if you use nginx, you will need to update the nginx configuration file to forward traffic to the API if the user hits `/swagger`:
```
    location /swagger {
      proxy_pass http://api:3000;
    }
```

**Comment by dmspils** [comment]
Easy! Confirmed working, thanks for the quick reply.
